name: chsm_modules_ci

on:
  push:
    branches: [ feature/fix_test_runs, master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: List out the directory
      run: tree ${{ github.workspace }}
      
    - name: Check cmake version
      run: cmake --version
     
    - name: Install Graphviz
      # You may pin to the exact commit or the version.
      # uses: tlylt/install-graphviz@b2201200d85f06f0189cb74d9b69208504cf12cd
      uses: tlylt/install-graphviz@v1.0.0
      
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -S ${{github.workspace}} -DCHSM_BUILD_TESTS=ON

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build -t all

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: |
        cmake --build . -t all
        ctest -VV 
      
